import hashlib
import json
import os
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import jinja2

from logger import logger


class ExportEngine:
    def __init__(
        self, templates_dir: str = "qgis/recipes", output_dir: str = "data/exports"
    ):
        self.templates_dir = Path(templates_dir)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(str(self.templates_dir)),
            autoescape=jinja2.select_autoescape(["html", "xml"]),
        )
        logger.debug(
            f"ExportEngine initialized with templates: {templates_dir}, output: {output_dir}"
        )

    def generate_export_bundle(
        self,
        base_filename: str,
        site_id: str,
        notes: List[Any],
        review_packet: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Generates an evidence package ZIP containing the generated map, metadata, notes, and a checksum manifest.
        base_filename should match the files generated by QGISRunner (e.g. 'recipe1_20260601_120000').
        """
        meta_file = self.output_dir / f"{base_filename}_meta.json"
        png_file = self.output_dir / f"{base_filename}.png"

        map_meta = {}
        if meta_file.exists():
            with open(meta_file, "r", encoding="utf-8") as f:
                map_meta = json.load(f)

        template = self.env.get_template("export_template.md")

        # Calculate checksum before writing to template
        # We will checksum the PNG and Meta files, then add the markdown to it
        manifest = ""

        def calc_sha256(filepath):
            if not Path(filepath).exists():
                return "FILE_NOT_FOUND"
            sha256 = hashlib.sha256()
            with open(filepath, "rb") as f:
                for block in iter(lambda: f.read(4096), b""):
                    sha256.update(block)
            return sha256.hexdigest()

        manifest += f"{calc_sha256(png_file)}  {png_file.name}\n"
        manifest += f"{calc_sha256(meta_file)}  {meta_file.name}\n"

        md_content = template.render(
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
            site_id=site_id,
            map_image_name=png_file.name,
            center_coords=map_meta.get("center_coordinates", "Unknown"),
            recipe_id=map_meta.get("recipe_id", "Unknown"),
            notes=notes,
            decision_state=map_meta.get("harness_decision", "Unknown"),
            review_packet=review_packet,
            checksum="PENDING",  # Will be updated after generation if we wanted a self-referential hash, but we just use manifest
        )

        md_file = self.output_dir / f"{base_filename}_report.md"
        with open(md_file, "w", encoding="utf-8") as f:
            f.write(md_content)

        manifest += f"{calc_sha256(md_file)}  {md_file.name}\n"

        manifest_file = self.output_dir / f"{base_filename}_manifest.txt"
        with open(manifest_file, "w", encoding="utf-8") as f:
            f.write(manifest)

        # Create ZIP
        zip_path = self.output_dir / f"{base_filename}_bundle.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            if png_file.exists():
                zf.write(png_file, arcname=png_file.name)
            if meta_file.exists():
                zf.write(meta_file, arcname=meta_file.name)
            zf.write(md_file, arcname=md_file.name)
            zf.write(manifest_file, arcname=manifest_file.name)

        logger.info(f"Generated export bundle: {zip_path}")
        return str(zip_path)
